name: Build C++ project with CMake
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y cmake g++
    - name: Build project with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make
